# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 4
    - nodejs_version: 5
    - nodejs_version: 6
    - nodejs_version: 7

install:
  - ps: Start-FileDownload 'https://download.microsoft.com/download/F/5/D/F5DBACEE-5B9A-4B4E-9382-18145C06F47D/MicrosoftAzureStorageEmulator.msi'
  - ps: msiexec /i MicrosoftAzureStorageEmulator.msi /quiet /qn /norestart /log install.log
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

before_test:
  - ps: '& "${Env:ProgramFiles(x86)}\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start'
  - ps: '& "${Env:ProgramFiles(x86)}\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" status'
  - ps: '& "${Env:ProgramFiles(x86)}\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" clear table'

test_script:
  - node --version
  - npm --version
  - npm test
