# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 0.10
  CODECLIMATE_REPO_TOKEN:
    secure: +dPx4KAE5xmYZBHquqBpuUnc5Rc/GKpydqfpst4eGfAD8MSTW+1Vuru+6QSnZVHMOi1ZlPZ5eK6QIP/7JpIMYr1VB92p/MifAWK0HHQODus=

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install -g codeclimate-test-reporter
  - npm install

build: off

before_test:
  - ps: '& "${Env:ProgramFiles(x86)}\Microsoft SDKs\Azure\Storage Emulator\WAStorageEmulator.exe" start'

test_script:
  - node --version
  - npm --version
  - npm test

after_test:
  - git checkout -qf master
  - git status
  - git log -1 --pretty=format:'%H'
  - git log -1 --pretty=format:'%ct'
  - codeclimate < coverage.lcov